# Generated by Django 4.2.5 on 2023-09-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellido')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('areas', models.CharField(choices=[('serv', 'Servicio'), ('coci', 'Cocina'), ('motor', 'Motorizados')], default=None, max_length=7, verbose_name='Areas')),
            ],
        ),
    ]
