# Generated by Django 4.2.5 on 2023-09-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='areas',
            field=models.CharField(choices=[('Servicio', 'Servicio'), ('Cocina', 'Cocina'), ('Motorizados', 'Motorizados')], default=None, max_length=12, verbose_name='Areas'),
        ),
    ]
