# Generated by Django 4.2.5 on 2023-09-20 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_personal_areas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=20)),
                ('producto', models.CharField(max_length=20)),
                ('cantidad', models.PositiveIntegerField()),
                ('fechaPeticion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personal')),
            ],
        ),
    ]
