# Generated by Django 4.2.5 on 2023-10-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteVentas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ganancia', models.PositiveIntegerField()),
                ('perdida', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
    ]
