# Generated by Django 4.2.5 on 2023-10-10 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_reporteventas_fecha_reporteventas_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporteventas',
            name='mes',
        ),
    ]
