# Generated by Django 4.2.5 on 2023-10-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_reporteventas_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteventas',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
