# Generated by Django 4.2.5 on 2023-10-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reporteventas_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteventas',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
