# Generated by Django 4.2.5 on 2023-10-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_reporteventas_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteventas',
            name='showGanancia',
            field=models.BooleanField(default=True),
        ),
    ]
